version: "3.8"
services:
  convey-mongo:
    container_name: convey-mongo
    image: mongo:4.4.18
    restart: on-failure
    volumes:
      - mongo:/data/db
      - ~/.aws:/root/.aws:ro
    command: mongod --noauth
    ports:
      - 27017:27017
    environment:
      - AWS_PROFILE=convey
volumes:
  mongo:
