version: "3.8"
services:
  convey-mongo:
    container_name: convey-mongo
    image: mongo:4.4.18
    restart: on-failure
    volumes:
      - mongo:/data/db
    command: mongod --noauth
    ports:
      - 27017:27017
volumes:
  mongo:
